# Generated by Django 5.1.5 on 2025-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('very_rare', 'Очень редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный'), ('artifact', 'Артефакт')], default='common', max_length=20, verbose_name='Редкость'),
        ),
    ]
