# Generated by Django 5.1.5 on 2025-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='role',
            field=models.CharField(choices=[('tank', 'Танк'), ('healer', 'Лекарь'), ('dps', 'Урон'), ('support', 'Поддержка')], max_length=50, verbose_name='Боевая роль'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='spellcasting_ability',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Характеристика заклинаний'),
        ),
    ]
