# Generated by Django 5.1.5 on 2025-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_characterclass_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='role',
            field=models.CharField(blank=True, choices=[('tank', 'Танк'), ('healer', 'Лекарь'), ('dps', 'Урон'), ('support', 'Поддержка')], default='dps', max_length=50, verbose_name='Боевая роль'),
        ),
    ]
