# Generated by Django 5.1.5 on 2025-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_characterclass_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='current_turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='turn_order',
            field=models.JSONField(default=list),
        ),
    ]
