# Generated by Django 5.1.5 on 2025-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_map_current_turn_index_map_turn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='spell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Картинка'),
        ),
    ]
