# Generated by Django 5.1.5 on 2025-07-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_item_x_item_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maps.map', verbose_name='Карта'),
        ),
    ]
