# Generated by Django 5.1.5 on 2025-07-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_iteminstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_find_diff',
            field=models.IntegerField(default=0, verbose_name='Сложность нахождения по умолчанию'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='find_diff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сложность нахождения'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='is_hidden',
            field=models.BooleanField(default=True, verbose_name='Спрятан?'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_items', to='maps.shape', verbose_name='Кто поднял предмет'),
        ),
    ]
