# Generated by Django 5.2.4 on 2025-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_shape_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='icon_type',
            field=models.CharField(choices=[('story', 'Сюжет'), ('trap', 'Ловушка'), ('chest', 'Сундук'), ('portal', 'Портал'), ('combat', 'Бой'), ('note', 'Заметка'), ('hidden', 'Скрытое'), ('trigger', 'Триггер'), ('npc', 'NPC'), ('sound', 'Звук')], default='story', max_length=20),
        ),
    ]
