# Generated by Django 5.2.4 on 2025-08-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_alter_mappoint_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='target_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_points', to='maps.room', verbose_name='Целевая комната (для порталов)'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='icon_type',
            field=models.CharField(choices=[('story', 'Сюжет'), ('trap', 'Ловушка'), ('chest', 'Сундук'), ('portal', 'Портал'), ('combat', 'Бой'), ('note', 'Заметка'), ('hidden', 'Скрытое'), ('trigger', 'Триггер'), ('npc', 'NPC'), ('sound', 'Звук'), ('slideshow', 'Слайдшоу')], default='story', max_length=20),
        ),
    ]
