# Generated by Django 5.1.5 on 2025-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_profile_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_maps',
        ),
    ]
