# Generated by Django 5.1.5 on 2025-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_map_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='shapes',
            field=models.JSONField(blank=True, default=list, verbose_name='Фигуры'),
        ),
    ]
