# Generated by Django 5.1.5 on 2025-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='features',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='class_features_by_level',
            field=models.JSONField(default=dict, verbose_name="Особенности по уровням (например, {'2': ['Охотничий натиск']})"),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Простой'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность освоения'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='has_magic',
            field=models.BooleanField(default=False, verbose_name='Использует магию'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='role',
            field=models.CharField(choices=[('tank', 'Танк'), ('healer', 'Лекарь'), ('dps', 'Урон'), ('support', 'Поддержка')], default='dps', max_length=50, verbose_name='Боевая роль'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='saving_throws',
            field=models.JSONField(default=list, verbose_name="Спасброски (например, ['STR', 'CON'])"),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starting_equipment',
            field=models.JSONField(default=list, verbose_name="Стартовое снаряжение (например, ['Меч', 'Щит'])"),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starting_features',
            field=models.JSONField(default=list, verbose_name='Умения 1 уровня'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный класс'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='primary_abilities',
            field=models.JSONField(default=list, verbose_name="Ключевые характеристики (например, ['WIS'])"),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='proficiencies',
            field=models.TextField(blank=True, null=True, verbose_name='Владения (оружие, доспехи, инструменты)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='ability_bonuses',
            field=models.JSONField(default=dict, verbose_name="Бонусы к характеристикам (например, {'STR': 2, 'CHA': 1})"),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='race',
            name='languages',
            field=models.JSONField(default=list, verbose_name="Языки (например, ['Общий', 'Эльфийский'])"),
        ),
        migrations.AlterField(
            model_name='race',
            name='traits',
            field=models.JSONField(default=list, verbose_name="Черты расы (например, ['Тёмное зрение', 'Стойкость'])"),
        ),
    ]
