# Generated by Django 5.1.5 on 2025-01-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_shapes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='shapes',
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('star', 'Star'), ('circle', 'Circle'), ('rectangle', 'Rectangle')], max_length=50, verbose_name='Тип фигуры')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('rotation', models.FloatField(default=0, verbose_name='Угол поворота')),
                ('fill', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Цвет заливки')),
                ('stroke', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет обводки')),
                ('stroke_width', models.FloatField(default=1.0, verbose_name='Толщина обводки')),
                ('num_points', models.IntegerField(blank=True, null=True, verbose_name='Количество точек (для звезд)')),
                ('inner_radius', models.FloatField(blank=True, null=True, verbose_name='Внутренний радиус (для звезд)')),
                ('outer_radius', models.FloatField(blank=True, null=True, verbose_name='Внешний радиус (для звезд)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='maps.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Фигура',
                'verbose_name_plural': 'Фигуры',
            },
        ),
    ]
