# Generated by Django 5.1.5 on 2025-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_remove_characterclass_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='traits',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Черты расы'),
        ),
    ]
