# Generated by Django 5.1.5 on 2025-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_race_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя персонажа'),
        ),
    ]
