# Generated by Django 5.1.5 on 2025-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_attack_image_characterclass_image_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата X'),
        ),
        migrations.AddField(
            model_name='item',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата Y'),
        ),
    ]
