# Generated by Django 5.1.5 on 2025-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_shape_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='wiewField',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Поле Видимости '),
        ),
    ]
