# Generated by Django 5.1.5 on 2025-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_shape_wiewfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='isPlayer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
