# Generated by Django 5.1.5 on 2025-07-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_item_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True, verbose_name='Координата X')),
                ('y', models.FloatField(blank=True, null=True, verbose_name='Координата Y')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Поднят с карты')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='maps.item', verbose_name='Шаблон предмета')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_instances', to='maps.map', verbose_name='Карта')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_instances', to='maps.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Экземпляр предмета на карте',
                'verbose_name_plural': 'Экземпляры предметов на карте',
            },
        ),
    ]
