# Generated by Django 5.1.5 on 2025-04-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_shape_isplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='rooms/backgrounds/', verbose_name='Фоновое изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание комнаты')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='maps.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['order'],
            },
        ),
    ]
