# Generated by Django 5.1.5 on 2025-04-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Фигура / Сущность', 'verbose_name_plural': 'Фигуры / Сущности'},
        ),
        migrations.AddField(
            model_name='shape',
            name='armor_class',
            field=models.IntegerField(default=10, verbose_name='Класс брони'),
        ),
        migrations.AddField(
            model_name='shape',
            name='attack_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус к атаке'),
        ),
        migrations.AddField(
            model_name='shape',
            name='character_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Класс персонажа'),
        ),
        migrations.AddField(
            model_name='shape',
            name='charisma',
            field=models.IntegerField(default=10, verbose_name='Харизма'),
        ),
        migrations.AddField(
            model_name='shape',
            name='constitution',
            field=models.IntegerField(default=10, verbose_name='Телосложение'),
        ),
        migrations.AddField(
            model_name='shape',
            name='current_hp',
            field=models.IntegerField(default=10, verbose_name='Текущее здоровье'),
        ),
        migrations.AddField(
            model_name='shape',
            name='damage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Урон (напр. 1d8+2)'),
        ),
        migrations.AddField(
            model_name='shape',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание или заметки'),
        ),
        migrations.AddField(
            model_name='shape',
            name='dexterity',
            field=models.IntegerField(default=10, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='shape',
            name='intelligence',
            field=models.IntegerField(default=10, verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_npc',
            field=models.BooleanField(default=False, verbose_name='Является NPC'),
        ),
        migrations.AddField(
            model_name='shape',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='shape',
            name='max_hp',
            field=models.IntegerField(default=10, verbose_name='Максимальное здоровье'),
        ),
        migrations.AddField(
            model_name='shape',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='shape',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Раса'),
        ),
        migrations.AddField(
            model_name='shape',
            name='speed',
            field=models.IntegerField(default=30, verbose_name='Скорость перемещения'),
        ),
        migrations.AddField(
            model_name='shape',
            name='strength',
            field=models.IntegerField(default=10, verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='shape',
            name='wisdom',
            field=models.IntegerField(default=10, verbose_name='Мудрость'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shapes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='isPlayer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='wiewField',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Поле видимости'),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная раса')),
                ('name', models.CharField(max_length=100, verbose_name='Название расы')),
                ('description', models.TextField(verbose_name='Описание расы')),
                ('traits', models.TextField(blank=True, null=True, verbose_name='Черты расы')),
                ('speed', models.IntegerField(default=30, verbose_name='Скорость перемещения')),
                ('size', models.CharField(choices=[('tiny', 'Крошечный'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой'), ('huge', 'Огромный')], default='medium', max_length=20, verbose_name='Размер')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Языки')),
                ('ability_bonuses', models.JSONField(default=dict, verbose_name="Бонусы к характеристикам (например, {'STR': 2, 'DEX': 1})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заклинания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень заклинания')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Школа магии')),
                ('casting_time', models.CharField(default='1 действие', max_length=100, verbose_name='Время накладывания')),
                ('range', models.CharField(default='На себя', max_length=100, verbose_name='Дистанция')),
                ('duration', models.CharField(default='Мгновенно', max_length=100, verbose_name='Длительность')),
                ('components', models.CharField(default='В', max_length=100, verbose_name='Компоненты')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Материалы (если есть)')),
                ('damage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Урон (например, 3d6)')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='Эффект/Механика')),
                ('is_concentration', models.BooleanField(default=False, verbose_name='Концентрация')),
                ('is_ritual', models.BooleanField(default=False, verbose_name='Ритуал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('gif', models.FileField(blank=True, null=True, upload_to='spells/gifs/', verbose_name='Гифка к заклинанию')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заклинания')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная раса')),
                ('description', models.TextField(verbose_name='Описание класса')),
                ('hit_dice', models.CharField(default='1d8', max_length=10, verbose_name='Кость хитов')),
                ('primary_abilities', models.JSONField(default=list, verbose_name="Основные характеристики (например, ['STR', 'CHA'])")),
                ('proficiencies', models.TextField(blank=True, null=True, verbose_name='Навыки и владения')),
                ('spellcasting_ability', models.CharField(blank=True, max_length=10, null=True, verbose_name='Характеристика заклинаний')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('spell_list', models.ManyToManyField(blank=True, to='maps.spell', verbose_name='Доступные заклинания')),
            ],
            options={
                'verbose_name': 'Класс персонажа',
                'verbose_name_plural': 'Классы персонажей',
            },
        ),
    ]
