# Generated by Django 5.1.5 on 2025-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_shape_options_shape_armor_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичное заклинание'),
        ),
    ]
