# Generated by Django 5.1.5 on 2025-07-09 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_mappoint_image_mappointimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.room'),
        ),
    ]
