# Generated by Django 5.1.5 on 2025-04-22 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_spell_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Сущность / Персонаж', 'verbose_name_plural': 'Сущности / Персонажи'},
        ),
        migrations.RemoveField(
            model_name='shape',
            name='description',
        ),
        migrations.AddField(
            model_name='shape',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='alignment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='allies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='bonds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='fears',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='fighting_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='flaws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='home_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='ideals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='insanity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='known_spells',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='legacy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='memories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='motivations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='notable_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='past_experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='patrons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='personality_traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='quests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='reputation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='resistances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='rivalries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='rumors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='sanity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='shape',
            name='vulnerabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='armor_class',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='character_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='current_hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='damage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='fill',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='shape',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shapes/'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='inner_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='isPlayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shape',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shape',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shape',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='maps.map'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='max_hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='num_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='outer_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='shape',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='stroke',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='stroke_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('star', 'Star'), ('circle', 'Circle'), ('rectangle', 'Rectangle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shape',
            name='wiewField',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shape',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape',
            name='y',
            field=models.FloatField(),
        ),
    ]
