# Generated by Django 5.1.5 on 2025-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_shape_options_remove_shape_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='charStory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='subclass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
