# Generated by Django 5.1.5 on 2025-04-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_openroom_roomplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openroom',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openroom',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='open_rooms', to='maps.map', verbose_name='Карта'),
            preserve_default=False,
        ),
    ]
