# Generated by Django 5.1.5 on 2025-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_openroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='last_opened_room_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID последней открытой комнаты'),
        ),
    ]
