# Generated by Django 5.1.5 on 2025-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_remove_map_full_card_map_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='full_card_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
