# Generated by Django 5.1.5 on 2025-05-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_map_full_card_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('title', models.CharField(max_length=100, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип иконки (например, 'NPC', 'враг', 'переход')")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость на карте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='maps.map', verbose_name='Карта')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.room', verbose_name='Комната (если связана)')),
            ],
            options={
                'verbose_name': 'Точка на карте',
                'verbose_name_plural': 'Точки на карте',
            },
        ),
    ]
