# Generated by Django 5.1.5 on 2025-05-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_alter_gamesession_options_remove_gamesession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='maps.map'),
        ),
    ]
