# Generated by Django 5.1.5 on 2025-05-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_alter_shape_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinsession',
            options={'verbose_name': 'Игрок в сессии', 'verbose_name_plural': 'Игроки в сессиях'},
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='players',
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.shape', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='maps.gamesession'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
