# Generated by Django 5.1.5 on 2025-05-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_shape_is_clone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='items/icons/', verbose_name='Иконка')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный'), ('artifact', 'Артефакт')], default='common', max_length=20, verbose_name='Редкость')),
                ('damage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Урон')),
                ('armor_bonus', models.IntegerField(default=0, verbose_name='Бонус к броне')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='Эффект')),
                ('is_magical', models.BooleanField(default=False, verbose_name='Магический')),
                ('is_consumable', models.BooleanField(default=False, verbose_name='Расходуемый')),
                ('charges', models.IntegerField(default=0, verbose_name='Заряды')),
                ('max_charges', models.IntegerField(default=0, verbose_name='Максимум зарядов')),
                ('slot_type', models.CharField(blank=True, choices=[('head', 'Голова'), ('body', 'Тело'), ('weapon', 'Оружие'), ('accessory', 'Аксессуар')], max_length=50, null=True, verbose_name='Слот экипировки')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('usable_by', models.JSONField(blank=True, default=list, verbose_name='Кем используется')),
                ('flavor_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Флэйвор-текст')),
                ('lore', models.TextField(blank=True, null=True, verbose_name='Лор')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Уникальный')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('value', models.IntegerField(default=0, verbose_name='Ценность (золото)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный предмет')),
                ('is_quest_item', models.BooleanField(default=False, verbose_name='Квестовый предмет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AddField(
            model_name='shape',
            name='created_from_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='current_ap',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shape',
            name='death_saves_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='death_saves_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='emotion_override',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='extra_attacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='favorite_gifs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shape',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_paralyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_permanently_dead',
            field=models.BooleanField(default=False, verbose_name='Персонаж окончательно мёртв'),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный персонаж'),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_stunned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='known_cantrips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='max_ap',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shape',
            name='permadeath',
            field=models.BooleanField(default=False, verbose_name='Перманентная смерть'),
        ),
        migrations.AddField(
            model_name='shape',
            name='prepared_spells',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='proficiency_bonus',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='shape',
            name='reaction_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='saving_throws',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shape',
            name='skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shape',
            name='spell_slots_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='spell_slots_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='statuses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shape',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('is_quick_slot', models.BooleanField(default=False)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='maps.shape')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.item')),
            ],
        ),
        migrations.AddField(
            model_name='shape',
            name='body_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_on_body', to='maps.item'),
        ),
        migrations.AddField(
            model_name='shape',
            name='head_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_on_head', to='maps.item'),
        ),
        migrations.AddField(
            model_name='shape',
            name='inventory',
            field=models.ManyToManyField(related_name='owners', through='maps.InventoryItem', to='maps.item'),
        ),
        migrations.AddField(
            model_name='shape',
            name='weapon_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_weapon', to='maps.item'),
        ),
    ]
