# Generated by Django 5.1.5 on 2025-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_item_shape_created_from_test_shape_current_ap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={},
        ),
        migrations.AddField(
            model_name='spell',
            name='area_of_effect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма зоны'),
        ),
        migrations.AddField(
            model_name='spell',
            name='area_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер зоны'),
        ),
        migrations.AddField(
            model_name='spell',
            name='classes_json',
            field=models.TextField(blank=True, null=True, verbose_name='Классы (JSON)'),
        ),
        migrations.AddField(
            model_name='spell',
            name='damage_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип урона'),
        ),
        migrations.AddField(
            model_name='spell',
            name='save_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип спасброска'),
        ),
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник'),
        ),
    ]
